### ISSUE TITLE
Add support for all sqlachemy pg drivers

### ISSUE THREAD

**Issue by graingert** [sqlalchemy-redshift/sqlalchemy-redshift#100]
eg pg8000 or psycopg2cffi; Also do not depend on psycopg2

**Comment by a5m0** [comment]
@graingert just wondering if/why this commit doesn't solve this issue? https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/commit/0440148ad83eda946a74987f9db1ad12b427859b
