### ISSUE TITLE
how to use CopyCommand

### ISSUE THREAD

**Issue by henrytxz** [sqlalchemy-redshift/sqlalchemy-redshift#109]
I have a working copy command that works in SQL Workbench/J. Mirroring it, I created a CopyCommand object. What do I do next to run the copy command against Redshift?

I see that there's a 
_sqlalchemy_redshift.commands.visit_copy_command(element, compiler, **kw)_
method. Looks like I'll have element = my_copy_command_object, is there more documentation on the compiler argument?

It'd be super if there's an end-to-end example somewhere, thanks a lot.

**Comment by henrytxz** [comment]
Can anyone help?

**Comment by graingert** [comment]
Hmm, it's odd this isn't in the documentation.  @adamchainz can you paste an example?

**Comment by henrytxz** [comment]
I found examples in
sqlalchemy-redshift/tests/test_copy_command.py
so I think I'm good. Thanks anyway.
