### ISSUE TITLE
Can't load plugin: sqlalchemy.dialects:psycopg2

### ISSUE THREAD

**Issue by rosner** [sqlalchemy-redshift/sqlalchemy-redshift#121]
Hey,

I just wanted to give it a spin. But I get a `NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:psycopg2`. I'm running 3.6.1 and installed `sqlalchemy 1.1.9` and `sqlalchemy-redshift 0.6.0`.

From there I just followed the docs and used my custom connection string to create the engine. However I'm not sure if this is actually a bug on this project.

**Comment by graingert** [comment]
@rosner I'm going to need the example code.

Can you create a minimal failing case and post it on github?

**Comment by jklukas** [comment]
In particular, what's in your connection string? From the output, I'm suspecting it might be prefixed with `psycopg2://` where it needs to be `redshift+psycopg2://`

**Comment by rosner** [comment]
@jklukas sorry I pasted the wrong exception message. I first tried with `redshift+psycopg2://user:password@host.us-east-1.redshift.amazonaws.com:5439/dev`

and then tried different things (`postgres://` and `redshift://` only for example).

**Comment by graingert** [comment]
@rosner I'm going to need the example code.

Can you create a minimal failing case and post it on github?

**Comment by rosner** [comment]
@graingert here's the snippet with which I can reproduce it:

```python
import sqlalchemy as sa
sa.create_engine('redshift+psycopg2://user:password@host.us-east-1.redshift.amazonaws.com:5439/dev')
```
I tried this in a clean venv.

**Comment by graingert** [comment]
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    import sqlalchemy as sa
ImportError: No module named 'sqlalchemy'
```

**Comment by graingert** [comment]
> I tried this in a clean venv.

perhaps this is your issue?

**Comment by graingert** [comment]
Seriously, can you actually create the project in GitHub and reproduce the failure with Travis.

**Comment by rosner** [comment]
Yeah you're right, I'm not really helpful without giving more context. Will try to reproduce it and get back.

**Comment by rosner** [comment]
Alright I finally got back to this. And I didn't manage to reproduce it with a travis setup. So I'm closing this and sorry for the "trouble" again. Thanks a ton for reacting that quickly. It's still puzzling what's going on in that specific venv but that's not an issue for this project.

**Comment by akashj08** [comment]
**Error : Can't load plugin: sqlalchemy.dialects:psycopg2**
I Have faced the same issue when set the variable clerny result backend:
`  AIRFLOW__CELERY__RESULT_BACKEND: "db+psycopg2://{{ .Values.postgresql.postgresqlUsername }}:{{.Values.postgresql.postgresqlPassword }}@airflow-postgresql-headless:{{ .Values.postgresql.service.port }}/airflow"
`
Reslove this issue by Changes the string value :
Must install python pip modules:
1.psycopg2-binary
2.sqlalchemy
3.sqlalchemy-redshift
`  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://{{ .Values.postgresql.postgresqlUsername }}:{{.Values.postgresql.postgresqlPassword }}@airflow-postgresql-headless:{{ .Values.postgresql.service.port }}/airflow"
`
