### ISSUE TITLE
Add support for MAXFILESIZE option in UNLOAD

### ISSUE THREAD

**Issue by atrigent** [sqlalchemy-redshift/sqlalchemy-redshift#123]
The UNLOAD command now has a very useful MAXFILESIZE option to control the maximum size of the produced files. The `UnloadFromSelect` construct in the dialect should have support for that.

http://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html

**Comment by jleclanche** [comment]
I wanted to implement this but then, what would the API look like? The syntax is `max-size [MB | GB]`. So we have two values to choose.

Choices:

* `UnloadFromSelect(max_file_size_mb=123)`, `UnloadFromSelect(max_file_size_gb=6.2)` (mutually-exclusive)
* `UnloadFromSelect(max_file_size=(123, "MB"))`, `UnloadFromSelect(max_file_size=(6.2, "GB"))` (tuple int or float with string)
* `UnloadFromSelect(max_file_size=(123, Size.MB))`, `UnloadFromSelect(max_file_size=(6.2, Size.GB))` (tuple int or float with enum)
* `UnloadFromSelect(max_file_size=123)`, `UnloadFromSelect(max_file_size=6.2 * 1024)` (only accept megabytes, auto-calculate when to show GB instead [if we even need to? Does the syntax allow for "6348 MB"?])

**Comment by graingert** [comment]
what sort of MB are these? MiB or MB?

**Comment by jleclanche** [comment]
Docs don't specify. Probably MiB, but would have to test.

**Comment by graingert** [comment]
once someone has found out, I think this should accept bytes and convert to "MB"

**Comment by jleclanche** [comment]
I don't think a bytes-level API is ideal, makes it a little impractical to use :/

**Comment by graingert** [comment]
```
class Size(enum.IntEnum):
    MiB = 1048576
    MB = 1000000
    GB =  1000000000
    GiB = 1073741824


UnloadFromSelect(max_file_size=123 * Size.MB)
```
