### ISSUE TITLE
Master branch failing tests to Redshift

### ISSUE THREAD

**Issue by jklukas** [sqlalchemy-redshift/sqlalchemy-redshift#131]
As discovered in https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/130#issuecomment-330875976 it looks like there's a change in Redshift behavior that's causing tests to fail in master.

We may simply need to update tests to match the new behavior.

**Comment by graingert** [comment]
@jklukas yup, noted. I've also merged a PR that drops support for python's not readily available on Travis.

**Comment by jleclanche** [comment]
I thought that should have been fixed in f975c4dc50f0ef4fefefef00bae6d8c8db65bf0f but I'm seeing some new failures, HTTP 500: https://travis-ci.org/sqlalchemy-redshift/sqlalchemy-redshift/jobs/279677504

**Comment by graingert** [comment]
@jleclanche ah you've got to ignore those 500s, it's just waiting for bigcrunch to boot up our redshift cluster

**Comment by jleclanche** [comment]
Ah okay. I see there's still constraint stuff failing; I didn't notice these issues because the tests are skipped locally. Weren't they fixed by a recent commit?

**Comment by graingert** [comment]
@jleclanche nope, the interpreter not found issues were fixed by you, but we've not got a fix for the new changes that amazon has made to Redshift

**Comment by jleclanche** [comment]
Do you know of any documentation or changelog/announcement about those changes?

**Comment by graingert** [comment]
nope, I'm not up to date, and they didn't notify us

**Comment by jleclanche** [comment]
So the most minimal I see is this statement:

```sql
    CREATE TABLE reflection_default_value (
        col1 INTEGER NOT NULL,
        col2 INTEGER DEFAULT 5,
        PRIMARY KEY (col1)
    ) DISTSTYLE EVEN
```

Which errors because in the tests, it gets cleaned into this statement:


```sql
    CREATE TABLE reflection_default_value (
        col1 INTEGER NOT NULL,
        col2 INTEGER DEFAULT 5,
        CONSTRAINT reflection_default_value_pkey PRIMARY KEY (col1)
    ) DISTSTYLE EVEN
```

It looks like redshift is adding a new constraint %s_pkey on primary key. I don't know if it was doing that before but somehow the introspection is finding it after the table is created and it errors because of the mismatch.

We could probably update the tests to match the new behaviour. Redshift constraints, aside from NOT NULL, have always been informational only so I don't think this changes anything... but if someone has contacted support about it to get clarifications that's something we should probably wait for.

**Comment by graingert** [comment]
@jleclanche I'd like to just update with that extra CONSTRAINT field that's being added

**Comment by jleclanche** [comment]
That's fine with me; you'll have to do it though, I can't run those tests locally since I don't have the credentials.

**Comment by graingert** [comment]
@jklukas are we ok to make a release without the tests passing?

**Comment by jklukas** [comment]
I'm fine with making a release. It's well understood what the problem is. I'd also like to see us get a release out with the most recent batch of features.

**Comment by jklukas** [comment]
@graingert - Do you want to issue a release, or want me to go ahead?

**Comment by graingert** [comment]
Can you do one, please?

I'm thinking 0.7.0?

**Comment by jklukas** [comment]
Will do.

**Comment by jklukas** [comment]
Published: https://pypi.python.org/pypi/sqlalchemy-redshift/0.7.0

**Comment by jklukas** [comment]
Looks like simply adding the CONSTRAINTs to the expected output doesn't work. If we add the CONSTRAINTs, the `test_reflection` tests pass, but the `test_definition` tests fail.

`test_definition` does `table_to_ddl(model.__table__)` which ends up calling:

```
CreateTable(table).compile(
        dialect=dialect.RedshiftDialect()
    )
```

Perhaps we can send some option in there to get Redshift and SQLAlchemy to agree.
