### ISSUE TITLE
redshift-ca-bundle.crt is out of date

### ISSUE THREAD

**Issue by wleftwich** [sqlalchemy-redshift/sqlalchemy-redshift#136]
After Amazon issued a new SSL root certificate for Redshift last week, I started getting connection failures with "sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL error: certificate verify failed".

I followed the instructions at http://docs.aws.amazon.com/redshift/latest/mgmt/connecting-transitioning-to-acm-certs.html and copied the new https://s3.amazonaws.com/redshift-downloads/redshift-ca-bundle.crt to ~/.postgresql/root.crt , which is the default location according to postgresql docs.

However, for the client to actually check the certificate, I had to provide the file path:
```
redshift+psycopg2://username:password@mycluster.us-east-1.redshift.amazonaws.com:5439/mydb?sslmode=verify-ca&sslrootcert=/home/mydir/.postgresql/root.crt
```

I guess this is because the module provides its own root certificate file, which is now out of date:
```python
def create_connect_args(self, *args, **kwargs):
        """
        Build DB-API compatible connection arguments.

        Overrides interface
        :meth:`~sqlalchemy.engine.interfaces.Dialect.create_connect_args`.
        """
        default_args = {
            'sslmode': 'verify-full',
            'sslrootcert': pkg_resources.resource_filename(
                __name__,
                'redshift-ca-bundle.crt'
            ),
        }
        cargs, cparams = super(RedshiftDialect, self).create_connect_args(
            *args, **kwargs
        )
        default_args.update(cparams)
        return cargs, default_args
```

**Comment by graingert** [comment]
Which version of sqlalchemy-redshift are you using?

**Comment by graingert** [comment]
0.7.0 currently contains an exact copy of https://s3.amazonaws.com/redshift-downloads/redshift-ca-bundle.crt

**Comment by wleftwich** [comment]
You're right of course. I thought I had done a `pip install -U`, but I
guess I hadn't. Sorry for the false alarm. And thanks for the very useful
library.
