### ISSUE TITLE
RelationKey.unquote only works when schema is None

### ISSUE THREAD

**Issue by vlasisva** [sqlalchemy-redshift/sqlalchemy-redshift#137]
Hi all,

In our database, we have a relation named _quote_ sitting inside a schema called _platform_.

Because the word quote is a Redshift keyword, the string representation of a dialect.RelationKey corresponding to this relation is platform."quote". This is all good.

The class RelationKey has an _unquote_ method, which returns a string representation of it with any "" quotes removed. Unfortunately, this method correctly removes the quotes only when the schema is None. In our case, the code is used with the schema non None (and equal to _platform_). What we see is that unquote, erroneously, does not remove the quotes (as it triggers only when str(RelationKey) both starts and ends with quotes).

I think a more comprehensive behaviour for the unquote method would be applying unquoting at both the schema names AND the relation names, so that unquoted(platform."quote") -> platform.quote.

This bug prevents sqlalchemy from reflecting our platform schema, ending with: 

File "/home/vlasisva/.local/lib/python3.5/site-packages/sqlalchemy_redshift/dialect.py", line 630, in _get_redshift_relation
    raise sa.exc.NoSuchTableError(key)
sqlalchemy.exc.NoSuchTableError: platform."quote"

Happy to elaborate, if above is not clear.

**Comment by graingert** [comment]
@vlasisva can you add a failing unit test that demos the problem?

**Comment by sacko87** [comment]
I'm not entirely sure how that step ever worked. The unquoted version of the key is a string and would never be in an array of `RelationKey`s. I'll have a deeper look at it. This is an issue we're currently coming across.

**Comment by huntcsg** [comment]
I'm hitting this and it's a pretty hard blocker for using Alembic for migrations.
I'd be happy to make a PR.

**Comment by jklukas** [comment]
> I'm hitting this and it's a pretty hard blocker for using Alembic for migrations.
> I'd be happy to make a PR.

Please do and I'd be happy to review.

**Comment by graingert** [comment]
@sacko87 started a PR here https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/167/files

**Comment by graingert** [comment]
I reopened it here: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/184
