### ISSUE TITLE
_get_column_info() missing 1 required positional argument: 'comment' in SQLAlchemy 1.2.0

### ISSUE THREAD

**Issue by jleclanche** [sqlalchemy-redshift/sqlalchemy-redshift#138]
https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/92852b7d2c720e7a088a788203b71c0c8447fa2e/sqlalchemy_redshift/dialect.py#L607

This breaks, because this was added:

http://docs.sqlalchemy.org/en/latest/changelog/changelog_12.html#change-3f38508932257c303017b1276f285c39

When it's called from `get_columns()`:

https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/92852b7d2c720e7a088a788203b71c0c8447fa2e/sqlalchemy_redshift/dialect.py#L406-L409

Because `comment` is missing from there.

**Comment by jleclanche** [comment]
Reference commit: https://bitbucket.org/zzzeek/sqlalchemy/commits/fadb8d61babb

**Comment by jleclanche** [comment]
Would it be crazy to add tests against sqlalchemy master branch to avoid getting caught up on short notice like this in the future?

**Comment by jklukas** [comment]
> Would it be crazy to add tests against sqlalchemy master branch to avoid getting caught up on short notice like this in the future?

I don't know that it would particularly help, since tests only get run when we new commits get sent to PRs. Months can go by without any activity here.

**Comment by jklukas** [comment]
This looks potentially messy if we want to maintain compatibility with SQLA pre-1.2.0 since the new `comment` parameter is the postgres driver doesn't have a default. We'd need to check the sqlalchemy library version or catch an error to dispatch to a different signature.

@graingert - Do you have thoughts about whether we could make SQAlchemy 1.2.0 the minimum required version for the next release?

**Comment by jleclanche** [comment]
> Months can go by without any activity here.

I think we can cron travis jobs nowadays.

**Comment by jklukas** [comment]
For review: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/139

**Comment by jklukas** [comment]
Addressed in 0.7.1: https://pypi.python.org/pypi?name=sqlalchemy-redshift&version=0.7.1&:action=display
