### ISSUE TITLE
How to specify compound sortkeys?

### ISSUE THREAD

**Issue by darwinyip** [sqlalchemy-redshift/sqlalchemy-redshift#175]
Since there is a `redshift_interleaved_sortkey=[]`, is there a way to do `redshift_compound_sortkey=[]`?

**Comment by manhnd1112** [comment]
+1. I have check the source but I can not where to define compound_sortkey :3 
Athought it is very important for improve performance

**Comment by jklukas** [comment]
See https://sqlalchemy-redshift.readthedocs.io/en/latest/ddl-compiler.html#sqlalchemy_redshift.dialect.RedshiftDDLCompiler

The parameter is `redshift_sortkey` if you want compound sortkey.
