### ISSUE TITLE
Type Synonyms not exported to top-level module

### ISSUE THREAD

**Issue by jcampbell** [sqlalchemy-redshift/sqlalchemy-redshift#181]
The sqlalchemy docs state that:

> As with all SQLAlchemy dialects, all UPPERCASE types that are known to be valid with PostgreSQL are importable from the top level dialect, whether they originate from sqlalchemy.types or from the local dialect

However, the redshift dialect currently does not allow importing known valid types. I believe the dialect should explicitly import valid redshift types to the top level so that it conforms to this standard.

Concretely, I believe the following should work:
`from sqlalchemy_redshift.dialect import BIGINT` (and same for all redshift types)

Sqlalchemy docs ref: https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#postgresql-data-types

**Comment by jklukas** [comment]
That sounds reasonable. PRs are welcome.

**Comment by jcampbell** [comment]
Awesome. Will submit a PR.
