### ISSUE TITLE
Conda (conda-forge) outdated

### ISSUE THREAD

**Issue by igorborgest** [sqlalchemy-redshift/sqlalchemy-redshift#196]
Congrats for the great job you have been doing!

I would like to request the update of the package on the conda-forge, the last version available there is `0.7.3`.

conda-forge: https://anaconda.org/conda-forge/sqlalchemy-redshift
conda-forge-repo: https://github.com/conda-forge/sqlalchemy-redshift-feedstock

P.S. As project owner you could ask privilegies on the repo and help to make new version available sooner.

P.P.S. Also posted on https://github.com/conda-forge/sqlalchemy-redshift-feedstock/issues/10

**Comment by igorborgest** [comment]
Seems that already has a PR ready to be merged: https://github.com/conda-forge/sqlalchemy-redshift-feedstock/pull/9

I'm maintaining a library [aws-data-wrangler](https://github.com/awslabs/aws-data-wrangler) that counts on sqlalchemy-redshift as a dependency. That said I would like to help you guys to keep the conda-forge update if you are not able to do it by your-selves. What you think?

**Comment by jklukas** [comment]
I know very little about conda-forge and was previously unaware of this package. Please do go ahead with updating that package if you are able to do so. It is neither created nor maintained by the folks here.

**Comment by igorborgest** [comment]
Thanks @jklukas.

Could please write down a note in the issue "allowing" my request?

https://github.com/conda-forge/sqlalchemy-redshift-feedstock/issues/11

**Comment by jklukas** [comment]
I don't want to get involved with making any decisions about the conda-forge package or how it's maintained. It looks from the issue there that they're happy to add you without any action on our end.

**Comment by igorborgest** [comment]
@jklukas perfect.
