### ISSUE TITLE
Create Materialized View with `table_attributes` configurable

### ISSUE THREAD

**Issue by ewengillies** [sqlalchemy-redshift/sqlalchemy-redshift#201]
Hi developers,

We've been using `sqlalchemy-redshift` for some time at my company, its great!

Specifically, we use it conjunction with [`sqlalchemy_utils.view`](https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/view.py) to create views on-the-fly.

Late last year, Redshift started supporting materialized views, excitingly with the option of specifying a dist style/key and/or sort keys.  See here:

https://docs.aws.amazon.com/redshift/latest/dg/materialized-view-create-sql-command.html

I think it'd be a neat feature to add a view-component to `sqlalchemy-redshift` so that we can have a function like:

```python
def create_materialized_view(
    name,
    selectable,
    table_attributes=None
    indexes=None,
    metadata=None,
    aliases=None
)
```

I'd be happy to implement such a feature if there is interest from the maintainers.  What are the thoughts on including this here?  If not, I can always write a new library, `sqlalchemy-redshift-views`, but I thought it might fit in the scope of this library.

**Comment by jklukas** [comment]
I could imagine a CreateMaterializedView DDLElement subclass could make sense for sqlalchemy-redshift. The maintainers don't have bandwidth to help guide new features in any depth, but I'd be willing to review if you're able to put together a PR that includes tests and documentation.

**Comment by ewengillies** [comment]
yes, sounds great! I'll post a PR once I've written the DDLElement.

**Comment by ewengillies** [comment]
thanks for the assistance @jklukas!  Merged and released, closing this now.
