### ISSUE TITLE
Testing AWS account is no longer funded

### ISSUE THREAD

**Issue by jklukas** [sqlalchemy-redshift/sqlalchemy-redshift#213]
The AWS account used to spin up short-lived Redshift clusters for CI in this repo is no longer funded. It was paid for by Simple (a former employer of mine), but Simple is shutting down and they have already removed the billing association for this account. It will be suspended shortly.

It's also worth noting that our CI on Travis is likely to stop working soon.

AFAIK, neither @graingert nor I have bandwidth to look for a new sponsor or make substantial updates to CI. This is a substantial risk to progress on this project.

**Comment by graingert** [comment]
@jklukas do you happen to know how much it cost to run this?

**Comment by jklukas** [comment]
The charge for January was $0.66. I can try to find more details on billing.

**Comment by jklukas** [comment]
That $0.66 could have been for only part of the month. It's unclear when the billing association was severed. From poking around a bit, I don't think I have any access to previous cost info, since it was directed to a separate billing account.

**Comment by jklukas** [comment]
I'm funding this now. As long as cost is only a few dollars a month, that should be okay.

**Comment by mswilson** [comment]
We (AWS) are able to provide service credits for testing this community-developed driver.

**Comment by jklukas** [comment]
This is sorted and credits are applied. We're still only spending a few dollars a month, so the credits should last quite a while.
