### ISSUE TITLE
Reflection code is not compatible with SQLAlchemy 1.4 beta

### ISSUE THREAD

**Issue by maksimleanovich** [sqlalchemy-redshift/sqlalchemy-redshift#214]
Hi, repo maintainers!
I just started a new project and decided to use the latest beta version of the SQLAlchemy in it to avoid 2.0 compatibility issues in the future. Unfortunately, it turns out they've made a couple of small changes that made it incompatible with the redshift-dialect.
Here they are:
https://github.com/sqlalchemy/sqlalchemy/commit/93b7767d00267ebe149cabcae7246b6796352eb8
and
https://github.com/sqlalchemy/sqlalchemy/commit/7362d454f46107cae4076ce54e9fa430c3370734

I've hacked it for my own purposes by making this little change here:
https://github.com/maksimleanovich/sqlalchemy-redshift/commit/ad9cce31cfad21957218768b30dc8a41a434c222

It works for me, but it will likely break 1.3 compatibility, and I'm not even sure it's logically correct.

Unfortunately, I'm not familiar with sqlalchemy and sqlalchemy-redshift code enough to make a proper change alone, but if someone gives me a bit of guidance, I'd be happy to submit a PR. Thanks!

**Comment by bastienboutonnet** [comment]
Chiming in here, I've also recently just ran into the same problem. I will try downgrading. However I was wondering if there was any plan to make this plugin compatible at some point and if there is anything I can do to help let me know.

Looks like @maksimleanovich is a good start but indeed I checked the branch by @jklukas and I have a feeling I don't understand the code well enough to have a stab at it. If you have some ideas or leads and you need a hand @jklukas let me know! I'd be happy to help

**Comment by jklukas** [comment]
This should hopefully be resolved now with 0.8.4: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/221
