### ISSUE TITLE
Compatibility with SQLAlchemy 2.0

### ISSUE THREAD

**Issue by matthewgdv** [sqlalchemy-redshift/sqlalchemy-redshift#222]
I figured I'd start an issue for `SQLAlchemy` 2.0 compatibility. Though 2.0 isn't yet released, `SQLAlchemy` has provided a mechanism for opting in to the 2.0 changes ahead of time by passing `create_engine(future=True)`.

As of `SQLAlchemy` 2.0, strings can no longer be passed to `Connection.execute` without first being wrapped in `text` constructs. This means that the queries `sqlalchemy-redshift` generates under the hood (for example, for table reflection), no longer work. The good news is that this is an incredibly easy backwards-compatible fix.

That said, there may be other issues that are currently being masked by the early-failing behaviour of strings being disallowed as executables. Maybe it would be worth running the test suite under 2.0 just to help gauge how much work will be involved in the update.

**Comment by jklukas** [comment]
This would indeed be interesting to evaluate. Should probably wait on this until https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/221 is sorted and we can start from a 1.4-compatible codebase.

**Comment by jklukas** [comment]
https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/221 is now merged, so it should be reasonable to start looking at 2.0 compatibility now.
