### ISSUE TITLE
SQLAlchemy 1.4 inspection and reflection raise `ObjectNotExecutableError`

### ISSUE THREAD

**Issue by br3ndonland** [sqlalchemy-redshift/sqlalchemy-redshift#225]
I'm on SQLAlchemy 1.4.21, psycopg2-binary 2.9.1, sqlalchemy-redshift 0.8.4, and Python 3.9.6.

This dialect was previously incompatible with the SQLAlchemy 1.4 inspection API (#214). I previously substituted a plain-text SQL statement to get table names. Example, given an instance of `Session` with a connection to a Redshift database:

```py
from sqlalchemy import text
from sqlalchemy.orm import Session


def get_db_table_names(session: Session) -> list[str]:
    """Get a list of table names from the database."""
    statement = text(
        "SELECT table_name "
        "FROM information_schema.tables "
        "WHERE table_schema='public';"
    )
    result = session.execute(statement)
    return result.scalars().all()
```

How this normally could be done with the [SQLAlchemy inspection API](https://docs.sqlalchemy.org/en/14/core/reflection.html#fine-grained-reflection-with-inspector) and the [first-party PostgreSQL dialects](https://docs.sqlalchemy.org/en/14/dialects/postgresql.html):

```py
from sqlalchemy import inspect
from sqlalchemy.orm import Session


def get_db_table_names(session: Session) -> list[str]:
    """Get a list of table names from the database."""
    engine = session.get_bind()
    inspector = inspect(engine)
    return inspector.get_table_names()
```

With sqlalchemy-redshift 0.8.4, the `inspector` instantiates successfully, but when `get_table_names()` runs, an `ObjectNotExecutableError` is raised:

```text
  return inspector.get_table_names()
File ".venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 266, in get_table_names
  return self.dialect.get_table_names(
File "<string>", line 2, in get_table_names
File ".venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
  ret = fn(self, con, *args, **kw)
File ".venv/lib/python3.9/site-packages/sqlalchemy_redshift/dialect.py", line 532, in get_table_names
  return self._get_table_or_view_names('r', connection, schema, **kw)
File ".venv/lib/python3.9/site-packages/sqlalchemy_redshift/dialect.py", line 651, in _get_table_or_view_names
  all_relations = self._get_all_relation_info(connection,
File "<string>", line 2, in _get_all_relation_info
File ".venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
  ret = fn(self, con, *args, **kw)
File ".venv/lib/python3.9/site-packages/sqlalchemy_redshift/dialect.py", line 722, in _get_all_relation_info
  result = connection.execute("""
File ".venv/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 280, in execute
  return self._execute_20(
File ".venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1579, in _execute_20
  util.raise_(
File ".venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
  raise exception
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: '\n        SELECT\n          c.relkind,\n          n.oid as "schema_oid",\n          n.nspname as "schema",\n          c.oid as "rel_oid",\n          c.relname,\n          CASE c.reldiststyle\n            WHEN 0 THEN \'EVEN\' WHEN 1 THEN \'KEY\' WHEN 8 THEN \'ALL\' END\n            AS "diststyle",\n          c.relowner AS "owner_id",\n          u.usename AS "owner_name",\n          TRIM(TRAILING \';\' FROM pg_catalog.pg_get_viewdef(c.oid, true))\n            AS "view_definition",\n          pg_catalog.array_to_string(c.relacl, \'\n\') AS "privileges"\n        FROM pg_catalog.pg_class c\n             LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace\n             JOIN pg_catalog.pg_user u ON u.usesysid = c.relowner\n        WHERE c.relkind IN (\'r\', \'v\', \'m\', \'S\', \'f\')\n          AND n.nspname !~ \'^pg_\'\n        ORDER BY c.relkind, n.oid, n.nspname;\n        '
```
An `ObjectNotExecutableError` is also seen when attempting to reflect (`sqlalchemy.MetaData().reflect(bind=engine)`).

Am I doing something incorrectly? Or can I help with a bugfix?

## Related

sqlalchemy-redshift/sqlalchemy-redshift#214
sqlalchemy-redshift/sqlalchemy-redshift#221
sqlalchemy-redshift/sqlalchemy-redshift#223

**Comment by jklukas** [comment]
SQLAlchemy 2.0 is going to disallow sending plain strings to `execute()`. In the stack trace above, it's hitting a method called `_execute_20` which makes me thing your environment is enforcing 2.0 compatibility. Is it possible that you have your environment configured to raise errors for constructs that are disallowed in 2.0?

https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/222 is about ensuring 2.0 compatibility, and this is one of the things that will need to be addressed before then.

**Comment by br3ndonland** [comment]
> SQLAlchemy 2.0 is going to disallow sending plain strings to `execute()`. In the stack trace above, it's hitting a method called `_execute_20` which makes me thing your environment is enforcing 2.0 compatibility. Is it possible that you have your environment configured to raise errors for constructs that are disallowed in 2.0?

Yes, good catch! I'm using the `future` flag on both the `Engine` and `Session`, as described in the [migration guide](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html). I'll keep an eye on #222 and look for ways I can help out. Thanks!
