### ISSUE TITLE
TIMESTAMPTZ is not displaying correct time per timezone

### ISSUE THREAD

**Issue by sumeetjo** [sqlalchemy-redshift/sqlalchemy-redshift#241]
Hello,

I tried to test out whether changing the timezone reflects correct value in TIMESTAMPTZ and TIMETZ datatypes. 
I found that TIMETZ displays correct time as per the timezone but TIMESTAMPTZ does not. 
Below is what I tested and notice that the TIMESTAMPTZ value is still displaying UTC value while TIMETZ is displaying New York time. 

result = session.query(RedshiftDBTable).all()

for row in result:
    print("SessionID:", row.session_id,"\n" "Region:", row.click_region,"\n" "Product:", row.product_id,
          "\n" "ClickDateTime:", row.click_datetime,"\n" "StreamTime:", row.stream_time)

OUTPUT-
SessionID: aa313fc2-40d0-11ec-a13a-127c89b78a9d 
Region: US / New York 
Product: 62325 
**ClickDateTime: 2021-10-20 10:12:40+00:00** 
StreamTime: 10:14:56+00:00

-----------
settz = "set timezone = 'America/New_York'"
session.execute(settz)
result = session.query(RedshiftDBTable).all()
for row in result:
    print("SessionID:", row.session_id,"\n" "Region:", row.click_region,"\n" "Product:", row.product_id,
          "\n" "ClickDateTime:", row.click_datetime,"\n" "StreamTime:", row.stream_time)

OUTPUT-
SessionID: aa313fc2-40d0-11ec-a13a-127c89b78a9d 
Region: US / New York 
Product: 62325 
**ClickDateTime: 2021-10-20 10:12:40+00:00** 
StreamTime: 05:14:56+00:00

**Comment by Brooke-white** [comment]
Hi Sumeet,

This issue stems from the database driver, not sqlalchemy-redshift. From our earlier chat you mentioned you are using redshift_connector, I'd recommend to open an issue for that repository if you continue to see issue after updating to the latest version.
