### ISSUE TITLE
Add HLLSKETCH

### ISSUE THREAD

**Issue by Steff94190** [sqlalchemy-redshift/sqlalchemy-redshift#245]
Hello,
I want to contribut and add feature to support dialet type HLLSKETCH.
I already done all dev for it and I want to push my the change in to the project.

example of code to add 
```
class HLLSKETCH(RedshiftTypeEngine, sa.dialects.postgresql.TEXT):
    """
    Redshift defines a HLLSKETCH column type
    https://docs.aws.amazon.com/redshift/latest/dg/c_Supported_data_types.html

    Adding an explicit type to the RedshiftDialect allows us follow the
    SqlAlchemy conventions for "vendor-specific types."

    https://docs.sqlalchemy.org/en/13/core/type_basics.html#vendor-specific-types
    """
    __visit_name__ = 'HLLSKETCH'

    def __init__(self):
        super(HLLSKETCH, self).__init__()

    def get_dbapi_type(self, dbapi):
        return dbapi.HLLSKETCH
```

best regards.

**Comment by Brooke-white** [comment]
Hey @Steff94190 ,

Thanks for opening this issue and volunteering to make a contribution :) I'd recommend to take a look at one of the PRs we've merged for datatype support, e.g. [this one for adding `SUPER` `GEOMETRY`](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/235), to get an idea of the sort of tests to add + all the places that need changes for a new datatype.

**Comment by Steff94190** [comment]
Thanks for your reply.
I already done all modification based on this (PR)[https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/235] but a don't have permision to push all my modification.
`sqlalchemy-redshift git:(add_hll_type) git push
remote: Permission to sqlalchemy-redshift/sqlalchemy-redshift.git denied to Steff94190.
fatal: impossible d'accéder à 'https://github.com/sqlalchemy-redshift/sqlalchemy-redshift.git/' : The requested URL returned error: 403`
