### ISSUE TITLE
Update contact info on code of conduct

### ISSUE THREAD

**Issue by jklukas** [sqlalchemy-redshift/sqlalchemy-redshift#258]
The [Enforcement section of the code of conduct](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/main/CODE_OF_CONDUCT.md#enforcement) lists my personal email as destination for reporting abusive behavior. Since I'm stepping down as a maintainer on this project, we should choose a new email address for reporting abuse.

**Comment by jklukas** [comment]
cc @graingert @Brooke-white

**Comment by Brooke-white** [comment]
@graingert  -- should we provide your e-mail here? If so, what e-mail would you like provided? I can open a PR if you'd like
