### ISSUE TITLE
Regression in v0.8.13: table reflection broken for non-superusers

### ISSUE THREAD

**Issue by adblair** [sqlalchemy-redshift/sqlalchemy-redshift#274]
It looks like v0.8.13 [introduced a get_table_oid() method](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/commit/ef35db87d0b03f5685dabccbe20cb7f536f8e335#diff-da4afac25892e729bdeca4533caf15820b269c54b5ad8bc7dbda7c47cdd76753R792-R812) that queries [SVV_TABLE_INFO](https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_TABLE_INFO.html), which is visible only to superusers:

```python
    @reflection.cache
    def get_table_oid(self, connection, table_name, schema=None, **kw):
        """Fetch the oid for schema.table_name.
        Return null if not found (external table does not have table oid)"""
        schema_clause = (
            "AND schema = '{schema}'".format(schema=schema) if schema else ""
        )

        result = connection.execute("""
                        SELECT table_id
                        FROM
                            SVV_TABLE_INFO
                        WHERE 1
                            {schema_clause}
                            AND "table" = '{table_name}';
                        """.format(
                                schema_clause=schema_clause,
                                table_name=table_name)
                            )

        return result.scalar()
```

This breaks table reflection for regular users.

**Comment by Brooke-white** [comment]
off the top of my head, we may be able to replace this query with `select '{schema}.{table_name}'::regclass::oid;`. apologies this made it into production, this should have been caught.

**Comment by adblair** [comment]
@Brooke-white Thanks for the rapid fix
