### ISSUE TITLE
Migration plan for moving to the sqlalchemy-redshift org

### ISSUE THREAD

**Issue by jklukas** [sqlalchemy-redshift/sqlalchemy-redshift#40]
There are some details we'll need to deal with when this project moves to the https://github.com/sqlalchemy-redshift org.

* Documentation
  * [ ] Make sure we're using sqlachemy-redshift and sqlalchemy_redshift consistently everywhere
  * [x] Make sure any references to the repo are correct
* [Read the Docs](https://readthedocs.org/projects/redshift-sqlalchemy)
  * [x] Change the url of docs to `sqlalchemy-redshift` (it's currently inverted)
  * [x] Set up a webhook on the repo so docs will build automatically.
* PyPI
  * [x] [Make redshift-sqlalchemy rely on sqlalchemy-redshift](https://github.com/binarydud/redshift_sqlalchemy/pull/33)

I wanted to make sure to document thoughts as I have them. Other things we'll need to keep in mind?

**Comment by graingert** [comment]
We don't have to worry too much about
> Make sure any references to the repo are correct

as I plan to move the repo, which creates HTTP redirects to the new location.

**Comment by jklukas** [comment]
Are we planning to change the name of the actual package to `sqlalchemy_redshift` to be consistent with the repo and project names? I think we should.

I'm pumped to see everything moving to the new homes.

**Comment by graingert** [comment]
@jklukas yup that's the plan.

I'd welcome a pull request that renamed the package and created a new package in the old location with the new locations imported for backwards compat

**Comment by jklukas** [comment]
See https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/58
