### ISSUE TITLE
Bigcrunch improvements

### ISSUE THREAD

**Issue by jklukas** [sqlalchemy-redshift/sqlalchemy-redshift#65]
@graingert - What would you think about hosting the bigcrunch repo on GitHub under the sqlalchemy-redshift org? It would make it easier to browse the code, and it would let us make PRs.

Another thought on bigcrunch - I'd be for upping the timeout. It looks like it's supposed to shut down 1 hour after the last created test session, and I've gotten burned by that a few times, meaning waiting for another whole round of shutdown and spinup to be able to run more tests. Maybe let it keep running for 4 hours?

**Comment by graingert** [comment]
Yup this makes total sense

**Comment by graingert** [comment]
@jklukas I've move the repo across, can you re-open this ticket on https://github.com/sqlalchemy-redshift/bigcrunch/issues please?
