### ISSUE TITLE
UnloadFromSelect does not support LIMIT clause.

### ISSUE THREAD

**Issue by briandailey** [sqlalchemy-redshift/sqlalchemy-redshift#69]
Parameters for `where` are all properly escaped, but adding a `.limit()` to the SQLAlchemy expression causes an error because it is unescaped (the parameter is passed in as `(%param1)`).

**Comment by graingert** [comment]
Do you have an example?

**Comment by briandailey** [comment]
```python
unload = UnloadFromSelect(select([sa.func.count(1)]).limit(1), ...s3params...)
print unload.compile().params
```

Note that in the `select` param you'll get something like this:

```
'select': u'SELECT count(1) AS count_1\n LIMIT :param_1'
```

`:param_1` is included in the SQL statement and throws an error.

**Comment by briandailey** [comment]
FWIW, the behavior of the old `redshift-sqlalchemy` package was that the `limit` parameter was passed to the unload command as a param, e.g. you would get:

```
unload.compile().params                                                             
{u'param_1': 5000000}
```

**Comment by briandailey** [comment]
Looks like this is an issue with older versions of sqlalchemy - may be able to resolve by upgrading it.
[This issue on sqlalchemy goes into more detail.](https://bitbucket.org/zzzeek/sqlalchemy/issues/3239/literal_binds-parameter-not-applied-to)

**Comment by graingert** [comment]
perhaps this would be better with an assert on the sqlalchemy version if the statement has a "._limit" attribute?

**Comment by briandailey** [comment]
That is a great idea - raise an exception to let the user know that they need to upgrade SQLAlchemy.
