### ISSUE TITLE
Problem with [waits] command for concurrent write queries

### ISSUE THREAD

**Issue by whitish** [sqlalchemy-redshift/sqlalchemy-redshift#76]
I m trying to reproduce an example from RS documentation using:
python 3.4
sqlalchemy-redshift==0.3.1
Here is an example from RedShift doc (http://goo.gl/V2PuZh):
```sql
begin;
[waits]
copy listing from ;
end;
```
But it throws an exception:
```python
ERROR - [RedShift] Programming Error: (psycopg2.ProgrammingError) syntax error at or near "["
LINE 1: begin; [waits] copy my_schema.my_table (userid, flag,...
               ^
[SQL: "begin; [waits] copy my_schema.my_table (userid, flag, campid, condition, ts) from 's3://mybucket/mydata' credentials 'aws_access_key_id=<my_aws_secret_key>;aws_secret_access_key=<my_aws_secret_access_key>' delimiter ','; end;"]
```

It works good without the **[waits]** operator. Is there any workaround so I can use **[waits]**?

**Comment by pior** [comment]
@whitish The doc linked is showing pseudo SQL: ``[waits]`` is not a SQL operation but an insight that the user must wait before running the next operation.

Not a bug in sqlalchemy-redshift.

**Comment by graingert** [comment]
That looks like quite bad documentation, you can report this to Amazon they're quite responsive
