### ISSUE TITLE
SQL_IDENTIFIER_RE issue

### ISSUE THREAD

**Issue by jseabold** [sqlalchemy-redshift/sqlalchemy-redshift#77]
I have encountered table names that look like `schema.table.name` and reflection is breaking because `SQL_IDENTIFER_RE.findall(key)` returns a list of length 3 in `dialect._get_schema_and_relation`.

**Comment by jseabold** [comment]
Seems like you may be able to get away with something like this since the schema / relation split doesn't need to meet the redshift identifier rules.

```identifiers = re.split("\.", key, 1)```

**Comment by graingert** [comment]
Do you have the example DDL?

**Comment by jseabold** [comment]
What else you need? The relname from `pg_catalogue.pg_class` for an ordinary table is `'schema.schema.table'`, so it was created with something like

```
create table schema."stupid.name" (id int);
```

and the `relname` won't reflect the quotes, when you query `pg_catalog.pg_class`.

**Comment by jseabold** [comment]
Ok...I'm remembering the issue again...

Why are you doing this? Honest question, I don't know. It seems like the only way you can have a key that's table.name is because you set the schema to None. If you don't do this, you don't have the problem. All of the quotes get stripped when the table information is stored, so we can't reliably use them in the regex and always splitting on the first period should work if you don't remove the schema.

https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/master/sqlalchemy_redshift/dialect.py#L635
