### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by jklukas** [sqlalchemy-redshift/sqlalchemy-redshift#81]
For most PRs, we are requiring tests, documentation, and CHANGES.rst notes. Sometimes we ask for these upfront, but sometimes we forget until later in the review, and it delays merging good changes.

We should provide a CONTRIBUTING.md both as a checklist for those doing review to make sure they aren't forgetting things, and for contributors so that they don't feel like requirements are popping up out of nowhere.

cc @graingert

**Comment by graingert** [comment]
Yes this would be great
