### ISSUE TITLE
SSL causing connection to fail

### ISSUE THREAD

**Issue by yergi** [sqlalchemy-redshift/sqlalchemy-redshift#84]
When I try to connect using `redshift+psycopg2` I end up with this error:
`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) sslmode value "verify-full" invalid when SSL support is not compiled in`
What do I need to do to actually connect to my redshift instance? I'm able to connect fine using `postgresql+psycopg2`

**Comment by graingert** [comment]
You probably need to have the openssl dev libraries installed when you
build psycopg2

I'm not supporting disabling TLS with this library.

**Comment by yergi** [comment]
Totally understandable and I wouldn't want to ask you to. Just been Googling for hours trying to figure out what I was missing to get this working. Thanks!

**Comment by graingert** [comment]
Maybe there's someone more familiar with psycopg2 that can assist on their
issue tracker,  mailing list or IRC
