### ISSUE TITLE
Support role based credentials for Copy and Unload command

### ISSUE THREAD

**Issue by mtrbean** [sqlalchemy-redshift/sqlalchemy-redshift#87]
We use role based credentials (http://docs.aws.amazon.com/redshift/latest/dg/copy-usage_notes-access-permissions.html#copy-usage_notes-access-role-based) instead of access and secret key. However it appears that UnloadFromSelect and CopyCommand do not support them.

**Comment by graingert** [comment]
That looks like an easy fix, do you want to make the PR?
