### ISSUE TITLE
Add support for AWS token/key credentials

### ISSUE THREAD

**Issue by postelrich** [sqlalchemy-redshift/sqlalchemy-redshift#89]
sqlalchemy redshift does not appear to support authenticating with AWS token/secret key.  I did find something that looks like it might in commands.py but there are no docs supporting how to supply the credentials if it does exist.

**Comment by graingert** [comment]
No you can't, you need to create postgres users with the admin account you created when you started the cluster

**Comment by postelrich** [comment]
Yea but I'm not talking postgres users, I'm talking about authenticating with aws if you don't username/password credentials.  AWS has secret key/token for accessing it programmatically http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSGettingStartedGuide/AWSCredentials.html

**Comment by graingert** [comment]
That's SQS not redshift
