### ISSUE TITLE
CopyCommand doesn't support REGION

### ISSUE THREAD

**Issue by adamchainz** [sqlalchemy-redshift/sqlalchemy-redshift#90]
I want to copy some files from S3 in a different region: https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-source-s3.html#copy-region

**Comment by graingert** [comment]
PRs accepted, you want to copy https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/master/sqlalchemy_redshift/commands.py#L563-L569

**Comment by graingert** [comment]
I tried to keep them in the same order as the documentation.

**Comment by dargueta** [comment]
I know this issue is ancient but I have a PR to fix it: #157
