### ISSUE TITLE
Redshift reserved words are not escaped

### ISSUE THREAD

**Issue by calleo** [sqlalchemy-redshift/sqlalchemy-redshift#94]
I got an error trying to create a table that had a column called "tag". The list of reserved words are here: http://docs.aws.amazon.com/redshift/latest/dg/r_pg_keywords.html

I fixed it in a very dirty way:

```
import sqlalchemy.dialects.postgresql.base as ps

REDSHIFT_RESERVED_WORDS = set("""aes128,aes256,all,allowoverwrite,analyse,
analyze,and,any,array,as,asc,authorization,backup,between,binary,blanksasnull,
both,bytedict,bzip2,case,cast,check,collate,column,constraint,create,
credentials,cross,current_date,current_time,current_timestamp,current_user,
current_user_id,default,deferrable,deflate,defrag,delta,delta32k,desc,disable,
distinct,do,else,emptyasnull,enable,encode,encrypt,encryption,end,except,
explicit,false,for,foreign,freeze,from,full,globaldict256,globaldict64k,grant,
group,gzip,having,identity,ignore,ilike,in,initially,inner,intersect,into,is,
isnull,join,leading,left,like,limit,localtime,localtimestamp,lun,luns,lzo,lzop,
minus,mostly13,mostly32,mostly8,natural,new,not,notnull,null,nulls,off,offline,
offset,oid,old,on,only,open,or,order,outer,overlaps,parallel,partition,percent,
permissions,placing,primary,raw,readratio,recover,references,respect,rejectlog,
resort,restore,right,select,session_user,similar,some,sysdate,system,table,tag,
tdes,text255,text32k,then,timestamp,to,top,trailing,true,truncatecolumns,union,
unique,user,using,verbose,wallet,when,where,with,without""".split(","))

ps.PGIdentifierPreparer.reserved_words = ps.PGIdentifierPreparer.reserved_words.union(helpers.REDSHIFT_RESERVED_WORDS)

```

Would be good if the redshift dialect would support this out of the box.

**Comment by graingert** [comment]
Does this happen with regular postgres databases under the postgres SQLalchemy dialect?

**Comment by calleo** [comment]
Haven't tried it, but "tag" seems to be Redshift specific.

**Comment by graingert** [comment]
Can you create a PR that overrides the Preparer in sqla-redshift with a subclass with those extra words in.

Also put those words in a line delimited file and load it with pkg_resource.resource_string

**Comment by graingert** [comment]
That's frustrating that they are different. Can you find out the differences. Are there some that redshift removed?

**Comment by rayrrr** [comment]
See http://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html

**Comment by jklukas** [comment]
I just ran into a problem with a column called `open`, which looks like another case of a word reserved in Redshift but not PG.

Looks like PG reserved words are documented in https://www.postgresql.org/docs/current/static/sql-keywords-appendix.html

**Comment by graingert** [comment]
Do we have a spec for redshift reserved words?

**Comment by rayrrr** [comment]
http://docs.aws.amazon.com/redshift/latest/dg/r_pg_keywords.html

**Comment by graingert** [comment]
@rayrrr you up for making a PR as described in https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/94#issuecomment-244738069?

**Comment by jklukas** [comment]
Here's a stab at getting a full list of Redshift-specific reserved words that aren't reserved by PG:

```
# File keywords.txt is a copy-paste of the table in https://www.postgresql.org/docs/current/static/sql-keywords-appendix.html
cat keywords.txt | grep '^[A-Z]*\treserved' | sed 's/\([A-Z]*\).*/\1/' > pg_reserved.txt

# File rs_reserved.txt is a copy-paste from http://docs.aws.amazon.com/redshift/latest/dg/r_pg_keywords.html
diff pg_reserved.txt rs_reserved.txt | grep '>' | sed 's/> //'
```

This gives the following:
```
AES128
AES256
ALLOWOVERWRITE
BACKUP
BETWEEN
BLANKSASNULL
BYTEDICT
BZIP2
CREDENTIALS
CURRENT_DATE
CURRENT_TIME
CURRENT_TIMESTAMP
CURRENT_USER
CURRENT_USER_ID
DEFLATE
DEFRAG
DELTA
DELTA32K
DISABLE
EMPTYASNULL
ENABLE
ENCODE
ENCRYPT
ENCRYPTION
EXPLICIT
GLOBALDICT256
GLOBALDICT64K
GZIP
IDENTITY
IGNORE
LUN
LUNS
LZO
LZOP
MINUS
MOSTLY13
MOSTLY32
MOSTLY8
NEW
NULLS
OFF
OFFLINE
OID
OLD
OPEN
PARALLEL
PARTITION
PERCENT
PERMISSIONS
RAW
READRATIO
RECOVER
RESPECT
REJECTLOG
RESORT
RESTORE
SESSION_USER
SNAPSHOT
SYSDATE
SYSTEM
TAG
TDES
TEXT255
TEXT32K
TIMESTAMP
TOP
TRUNCATECOLUMNS
WALLET
WITHOUT
```

**Comment by graingert** [comment]
@jklukas are there any that are reserved by PG but not Redshift?

**Comment by jklukas** [comment]
These are reserved by PG but not Redshift:
```
› diff pg_reserved.txt rs_reserved.txt | grep '<' | sed 's/< //'
ASYMMETRIC
COLLATION
CONCURRENTLY
FETCH
LATERAL
RETURNING
SYMMETRIC
TABLESAMPLE
VARIADIC
WINDOW
```

**Comment by jklukas** [comment]
That's based on list of reserved words in current PG. I'll be most of those are new since whichever 8.x Redshift was originally forked from.

**Comment by rayrrr** [comment]
Sure, I'll give it a go this weekend.

**Comment by jklukas** [comment]
I'm going to pick this up.

**Comment by jklukas** [comment]
See https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/117

**Comment by jklukas** [comment]
Fixed by https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/pull/117
