### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by jfhbrook** [sqlalchemy-redshift/sqlalchemy-redshift#99]
The last release was in April, and there have been a whole mass of patches made since then.

**Comment by graingert** [comment]
It's only:

    Support role-based access control in COPY and UNLOAD commands (Issue #88)
    Increase max_identifier_length to 127 characters (Issue #96)

**Comment by jfhbrook** [comment]
and those are significant! You should release them.

**Comment by graingert** [comment]
@jfhbrook I'll cut a release if you add a test for #86

**Comment by graingert** [comment]
See the [milestone](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/milestone/2) for more details

**Comment by jklukas** [comment]
0.6.0 is live on PyPI.
